### PR TITLE
create a Set type that extends the two existing Set implementations with many new methods

### PR DESCRIPTION
**Pull request by dans-stuff**
thanks to generics, we can do some pretty fancy stuff here! extending a generic type into a more rich generic type. 

this new type embeds the existing generic set as a generic interface. performance was not a consideration here, just code simplicity and features.

### CODE REVIEW

**Review by yoursunny — COMMENTED** [review]
I suggest adding godoc to the methods, explaining what they do and their limitations if any.

**Comment by zyedidia** [comment]
Pretty cool! I agree that some doc comments would be useful here.

**Comment by hlindberg** [comment]
Can this be released? This is not available when you get the latest v1.1.0 release?

**Comment by zyedidia** [comment]
I have made a new release. Thanks!

**Pull request merged**
