### PR TITLE
Add splay

### PR DESCRIPTION
**Pull request by zjkmxy**
Hello. I want to contribute [splay](https://en.wikipedia.org/wiki/Splay_tree), a fancy BST that supports range aggregation, like query the min value of a key range.

### CODE REVIEW

**Comment by zyedidia** [comment]
Does aggregation have to be implemented within the splay tree implementation like this? The splay tree data structure seems independent from range aggregation, so perhaps we could provide a basic implementation and an API that would allow users to implement aggregation on top of it if they want. I haven't looked too closely at the code yet though.

**Comment by zjkmxy** [comment]
Thank you for reviewing this. Aggregation could be independent of splay tree. Let me separate them,

**Comment by zjkmxy** [comment]
Hello. I have separated aggregators and the splay. Could you please review the commit again? Thanks.

**Comment by zyedidia** [comment]
Sorry for the delay, I will get around to this in a bit.

**Comment by zyedidia** [comment]
Unfortunately I think the use-case for this particular implementation is too complex/niche for this library. I think it might be better as a separate library rather than within this one.

**Pull request closed without merging**
